// Code generated by ent, DO NOT EDIT.

//go:build tools
// +build tools

// Package internal holds a loadable version of the latest schema.
package internal

const Schema = `{"Schema":"projectname/db/schema","Package":"projectname/db","Schemas":[{"name":"User","config":{"Table":""}}],"Features":["schema/snapshot","sql/upsert","intercept","namedges"]}`
