// Code generated by ent, DO NOT EDIT.

package db

import (
	"projectname/db/schema"
	"projectname/db/user"
	"projectname/db/usergroup"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescName is the schema descriptor for name field.
	userDescName := userFields[0].Descriptor()
	// user.NameValidator is a validator for the "name" field. It is called by the builders before save.
	user.NameValidator = userDescName.Validators[0].(func(string) error)
	usergroupFields := schema.UserGroup{}.Fields()
	_ = usergroupFields
	// usergroupDescName is the schema descriptor for name field.
	usergroupDescName := usergroupFields[0].Descriptor()
	// usergroup.NameValidator is a validator for the "name" field. It is called by the builders before save.
	usergroup.NameValidator = usergroupDescName.Validators[0].(func(string) error)
}
